import sys

from exception import CustomException

print(sys.path)
